### ISSUE TITLE
Possible bug in chat restore

### ISSUE THREAD

**Issue by LeoFCardoso** [gaubert/gmvault#152]
- What version of Gmvault do you use ?
Gmvault v1.8.1-beta

- On what Operating System (Linux flavour, MacOSX, Win7/XP/Vista) ?
Ubuntu Linux (Linux NAS 3.2.0-55-generic-pae #85-Ubuntu SMP Wed Oct 2 14:03:15 UTC 2013 i686 i686 i386 GNU/Linux)

- Type of requests (Bug, documentation issue, features) ?
Bug

- Explain the request subject (issue details, feature details):
I'm receiving this error when try to restore chats from one account to another. Here are the debug mode messages.

[2013-11-14 11:06]:CRITICAL:gmvault:Pushing chat content with id 1229571740457151930.
[2013-11-14 11:06]:DEBUG:gmvault:Subject = Conversa com Andre Locke Tozzini.
[2013-11-14 11:06]:DEBUG:imap_utils:Before to Append email contents
[2013-11-14 11:06]:DEBUG:imap_utils:Appended data with flags [u'\\Seen'] and internal time 2007-02-27 19:14:07. Operation time = 0.982861995697.
res = [APPENDUID 598133567 294383] (Success)

[2013-11-14 11:06]:DEBUG:imap_utils:result_uid = 294383
[2013-11-14 11:06]:DEBUG:gmvault:label = Lista Zoação

[2013-11-14 11:06]:ERROR:gmvault:Catch the following exception 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)
[2013-11-14 11:06]:ERROR:gmvault:'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault.py", line 968, in restore_chats
    labels_to_apply[str(label)] = imap_id #add in multimap
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)
[2013-11-14 11:06]:CRITICAL:gmv:Error: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128).

[2013-11-14 11:06]:CRITICAL:gmv:=== Exception traceback ===
[2013-11-14 11:06]:CRITICAL:gmv:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmv_cmd.py", line 763, in run
    self._restore(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmv_cmd.py", line 635, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault.py", line 883, in restore
    self.restore_chats(extra_labels, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault.py", line 979, in restore_chats
    handle_restore_imap_error(err, gm_id, db_gmail_ids_info, self)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault.py", line 84, in handle_restore_imap_error
    raise the_exception
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)

[2013-11-14 11:06]:CRITICAL:gmv:=== End of Exception traceback ===

- In case of bug or issue, please detail how we can reproduce the problem:
Try to restore chats with some "offending" char (I'm supposing).

leonardo@NAS:~/Documentos/GMailVault$ find . -name 1229571740457151930*
./quarantine/1229571740457151930.meta
./db/chats/subchats-1/1229571740457151930.eml.gz
./db/chats/subchats-6/1229571740457151930.meta
./db/chats/subchats-6/1229571740457151930.eml.gz
./db/chats/subchats-3/1229571740457151930.meta
./db/chats/subchats-3/1229571740457151930.eml.gz

**Comment by gaubert** [comment]
solved in 1.9
