### ISSUE TITLE
unicode error in gmvault.py

### ISSUE THREAD

**Issue by erikvanzijst** [gaubert/gmvault#158]
I'm running 1.8.1-beta on Linux and I'm seeing crashes on unicode conversions:

    Process email num 159 (imap_id:179) from 2007-06.
    Error: 'ascii' codec can't encode characters in position 1126-1128: ordinal not in range(128).

    === Exception traceback ===
    Traceback (most recent call last):
      File "/home/erik/work/env/gmvault/local/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 759, in run
        self._sync(args, credential)
      File "/home/erik/work/env/gmvault/local/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 677, in _sync
        restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
      File "/home/erik/work/env/gmvault/local/lib/python2.7/site-packages/gmv/gmvault.py", line 602, in sync
        self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
      File "/home/erik/work/env/gmvault/local/lib/python2.7/site-packages/gmv/gmvault.py", line 565, in _sync_emails
        imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
      File "/home/erik/work/env/gmvault/local/lib/python2.7/site-packages/gmv/gmvault.py", line 523, in _common_sync
        handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
      File "/home/erik/work/env/gmvault/local/lib/python2.7/site-packages/gmv/gmvault.py", line 154, in handle_sync_imap_error
        raise the_exception
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 1126-1128: ordinal not in range(128)

    === End of Exception traceback ===

Environment:

    $ pip freeze
    IMAPClient==0.10.2
    Logbook==0.3
    argparse==1.2.1
    gdata==2.0.17
    gmvault==1.8.1-beta
    wsgiref==0.1.2

**Comment by grondinm** [comment]
Not sure why i'm only noticing this now but a gmv-1.8.2 branch exists in the repo. Building/installing with this branch seems to fix this issue...for me at least running arch 64-bit.

**Comment by stp-ip** [comment]
I am running gmv-1.8.2 branch and get a UnicodeEncodeError from mbox. Not sure, if it is a library bug.
Here is the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmv_cmd.py", line 771, in run
    self._export(args)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmv_cmd.py", line 616, in _export
    exporter.export()
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 69, in export
    default_folder = self.GM_ALL, use_labels = True)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 104, in export_ids
    self.mailbox.add(msg, folder, meta[gmvault_db.GmailStorer.FLAGS_K])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 288, in add
    self.subdir(folder).add(mmsg)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 276, in subdir
    self.open[cur_label] = mailbox.mbox(mbox_path)
  File "/usr/lib/python2.7/mailbox.py", line 828, in __init__
    _mboxMMDF.__init__(self, path, factory, create)
  File "/usr/lib/python2.7/mailbox.py", line 571, in __init__
    f = open(self._path, 'rb+')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 56: ordinal not in range(128)
```

I tried to find the label (I assume it is due to unicode within a label) and found another UnicodeEncodeError:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmv_cmd.py", line 771, in run
    self._export(args)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmv_cmd.py", line 616, in _export
    exporter.export()
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 69, in export
    default_folder = self.GM_ALL, use_labels = True)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 82, in export_ids
    exported_labels = "labels " + self.printable_label_list(self.labels)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.8.1_beta-py2.7.egg/gmv/gmvault_export.py", line 75, in printable_label_list
    labels = [l.encode('ascii', 'backslashreplace') for l in labels]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

**Comment by stp-ip** [comment]
Fixed the issue for me temporarily by renaming my label "ß" to "ss" and resyncing (full mode) all mails on top of the old db. Now no unicode issues persist it seems. Still a code fix would be appreciated.

**Comment by gaubert** [comment]
@erikvanzijst @stp-ip and all Long time no see. I am back and I need your help here to solve that issue. I cannot just add change write(data) to write(data.encode('utf-8')) because it will create other issues. I can explain myself here. In your case the encode to utf-8 is straight forward because there was no decoding to perform prior to write the string in the file.

I have a reproducible case where the email is a mulitpart MIME and contains multiple encoding.
One encoding is ISO-8859-1 (Latin-1) so when I change write to write(data.encode('utf-8'), I get the following exception:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 3614: invalid continuation byte.

This is because the encode method assumes that it is ascii and try to encode ascii. 
I first need to decode with the right encoding (LATIN-1) here and encode in UTF-8.
So that would mean that I need to parse the email with an email parser and then store it on disk.
I could maybe do it with the email package I have to check.

There might be a way also to avoid interpreting the character content as I never touch the email content and do not care and would like to store it as it is as a byte array. Do you think it is possible ?

Another solution could be try some default encodings and on error try the next one (ascii, then utf-8).

Thanks for your help

**Comment by gaubert** [comment]
I forgot to mention I have this exception because first you need to decode as unicode and then you have to encode as utf-8. It is when I decode that there is the issue.

**Comment by gaubert** [comment]
Who wants to make a test to validate the next version ?

I have somehow fixed the problem. I try to guess the encoding with chardet and if it fails I use the ignore option of encode to eat the character such that the email can be saved.

In the next version I intend to move to python 3 and this should solve my issue because in python by default all strings are unicode so I will not have to decode the string.

**Comment by gaubert** [comment]
@erikvanzijst @grondinm @kelvinhammond @ripdog @ellis @stp-ip Solved new version support Oauth2. Please check new release v1.9. It is a compromise because there is no complete solution for that problem as you need to guess the encoding to decode.

**Comment by grondinm** [comment]
Thank you so much for keeping working on this.

**Comment by gaubert** [comment]
You are welcome. Please report problems you would find so that I can fix
them.

Guillaume
