### ISSUE TITLE
Unable to export to offline imap in Windows

### ISSUE THREAD

**Issue by mpfraser** [gaubert/gmvault#162]
I have set permissions on the folder and sub-folders to Full for "everyone" as well as my user.

gmvault-shell>gmvault.bat export -t offlineimap c:\temp

Export gmvault-db as a offlineimap mailbox.
Start emails export for default labels.
Error: [Error 123] The filename, directory name, or volume label syntax is incorrect.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.pyc", line 771, in run
  File "gmv\gmv_cmd.pyc", line 616, in _export
  File "gmv\gmvault_export.pyc", line 69, in export
  File "gmv\gmvault_export.pyc", line 104, in export_ids
  File "gmv\gmvault_export.pyc", line 177, in add
  File "mailbox.pyc", line 279, in add
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

=== End of Exception traceback ===

**Comment by wds52** [comment]
Offlineimap not working in version 1.9.1 as well:

_gmvault-shell>gmvault export -t offlineimap C:\mail-OIM-dir

Create defaults in C:\Documents and Settings\Owner/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Export gmvault-db as a offlineimap mailbox.
Start emails export for default labels.
Error: [Error 123] The filename, directory name, or volume label syntax is incorrect.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 758, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 606, in _export
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault_export", line 69, in export
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault_export", line 104, in export_ids
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault_export", line 177, in add
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\mailbox", line 298, in add
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

=== End of Exception traceback ===_

Any insight as to a fix or workaround?
