### ISSUE TITLE
Crash when export with label contains a question mark?

### ISSUE THREAD

**Issue by jtu100** [gaubert/gmvault#180]
If I run an export operation on Windows like so:

    gmvault export d:\emails

I get the following exception:
```
Error: [Errno 22] invalid mode ('rb+') or filename: u'd:\\emails\\programming ideas?'.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.pyc", line 771, in run
  File "gmv\gmv_cmd.pyc", line 616, in _export
  File "gmv\gmvault_export.pyc", line 69, in export
  File "gmv\gmvault_export.pyc", line 104, in export_ids
  File "gmv\gmvault_export.pyc", line 288, in add
  File "gmv\gmvault_export.pyc", line 276, in subdir
  File "mailbox.pyc", line 784, in __init__
  File "mailbox.pyc", line 550, in __init__
IOError: [Errno 22] invalid mode ('rb+') or filename: u'd:\\emails\\programming ideas?'

=== End of Exception traceback ===
```

**Comment by gaubert** [comment]
This will be solved by the new version I am working. I treated unicode labels differently.

**Comment by gaubert** [comment]
it is export. I had not seen it. It is not in a good state. It was developed by a contributor and I was never fully satisfied with it.
