### ISSUE TITLE
Sync error: command UID illegal in state NONAUTH, only allowed in states SELECTED

### ISSUE THREAD

**Issue by cdzombak** [gaubert/gmvault#183]
The same sync command I run every week today ran for a while, then resulted in the following error. Has anyone else seen this/does anyone have any suggestions?

The command I'm running is: `gmvault-v1.8.1-beta/bin/gmvault sync email@domain -d Backups/gmvault-db`

```
== Processed 1500 emails in 10s. 1354 left to be stored (time estimate 9s).==

Received an IMAP abort error. Wait 1 seconds and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from /Users/me/.gmvault/email@domain.oauth.

Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from /Users/me/.gmvault/email@domain.oauth.

Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from /Users/me/.gmvault/email@domain.oauth.

Error when reaching Gmail server. Wait 1 seconds and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from /Users/me/.gmvault/email@domain.oauth.

Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get XOAuth credential from /Users/me/.gmvault/email@domain.oauth.

Error while fetching message with imap id 2960.

=== Exception traceback ===

Traceback (most recent call last):
  File "gmv/gmvault.pyc", line 180, in individual_fetch
  File "gmv/imap_utils.pyc", line 174, in wrapper
  File "gmv/imap_utils.pyc", line 109, in reconnect
error: command UID illegal in state NONAUTH, only allowed in states SELECTED

=== End of Exception traceback ===

Error: command UID illegal in state NONAUTH, only allowed in states SELECTED.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv/gmv_cmd.pyc", line 759, in run
  File "gmv/gmv_cmd.pyc", line 677, in _sync
  File "gmv/gmvault.pyc", line 602, in sync
  File "gmv/gmvault.pyc", line 565, in _sync_emails
  File "gmv/gmvault.pyc", line 464, in _common_sync
  File "gmv/gmvault.pyc", line 209, in next
  File "gmv/gmvault.pyc", line 183, in individual_fetch
  File "gmv/gmvault.pyc", line 152, in handle_sync_imap_error
error: command UID illegal in state NONAUTH, only allowed in states SELECTED

=== End of Exception traceback ===
```

**Comment by gaubert** [comment]
Gmvault seem to have a problem with the mail with imap id 2960.
I would need to see to understand. Alternatively if it is a spam email you could delete it.
I am also working on a new version that is fixing some unicode encoding issue which often is the source of issues similar to yours. 
I could give you a new version within one or two weeks for testing purposes.

**Comment by gaubert** [comment]
Solved new version support Oauth2. Please check new release v1.9.
