### ISSUE TITLE
[Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/httplib2-0.9.egg-info/top_level.txt'

### ISSUE THREAD

**Issue by jprice** [gaubert/gmvault#184]
I get the following when I try to install via pip:

```
❯❯ pip install --verbose --pre gmvault --allow-external IMAPClient
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2727, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 700, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2727, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2227, in activate
    self.insert_on(path)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2334, in insert_on
    self.check_version_conflict()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2373, in check_version_conflict
    for modname in self._get_metadata('top_level.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2221, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1209, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1201, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1316, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/httplib2-0.9.egg-info/top_level.txt'
```

**Comment by gaubert** [comment]
need to fix the deployment with pip

Hi I am back. I am working on a new version that will first fix the followings and later on a new version will provide additional fixes and features
- allow connection with oauth2
- support of latest imapclient
- deployment with pip and for windows and mac osx

I hope to have it ready within 3 weeks.

**Comment by gaubert** [comment]
Solved new version support Oauth2. Please check new release v1.9.
