### ISSUE TITLE
Encryption Bug

### ISSUE THREAD

**Issue by HaoZeke** [gaubert/gmvault#185]
This happens whenever the -e flag is used. Otherwise things are ok. Arch Linux. gmv-1.8.2

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 759, in run
    self._sync(args, credential)
  File "/usr/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 677, in _sync
    restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/lib/python2.7/site-packages/gmv/gmvault.py", line 602, in sync
    self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
  File "/usr/lib/python2.7/site-packages/gmv/gmvault.py", line 565, in _sync_emails
    imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
  File "/usr/lib/python2.7/site-packages/gmv/gmvault.py", line 523, in _common_sync
    handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
  File "/usr/lib/python2.7/site-packages/gmv/gmvault.py", line 154, in handle_sync_imap_error
    raise the_exception
AttributeError: __exit__

=== End of Exception traceback ===

**Comment by gaubert** [comment]
yep need to support another encryption lib.
I am working on a new version that will first fix the followings and later on a new version will provide additional fixes and features
- allow connection with oauth2
- support of latest imapclient
- deployment with pip and for windows and mac osx

I hope to have it ready within 3 weeks.

**Comment by michaelmior** [comment]
If this is relevant, I notice that this works the first time I run sync on an empty DB. It only breaks when I try to run again without clearing out the DB first.

**Comment by gaubert** [comment]
@michaelmior encryption is broken on 1.9.0. I need to fix it in the next version.

**Comment by guaycuru** [comment]
Any news on this? I cannot use gmvault anymore since upgrading to 1.9 :\

**Comment by cbknutson** [comment]
+1 on this issue. I am broken since 1.9. Downgrade brings me back to Oauch1 unsupported by google.
