### ISSUE TITLE
Error using two legged oauth

### ISSUE THREAD

**Issue by yo-que-se** [gaubert/gmvault#201]
Hello.
I'm using gmvault v1.8.1 beta.
I have problems using the two legged oauth with my corporte google apps accounts.
I send you the details:

>gmvault sync account@mydomain.com --2-legged-oauth -d G:\gmvault-db\db\account@mydomain.com

Use gmvault-db located in G:\gmvault-db\db\account@mydomain.com.

Activate Gmvault db cleaning.
Authentication performed with Gmail XOAuth token.

Get XOAuth credential from ./.gmvault/account@mydomain.com.oauth.

Successfully read oauth credentials.

Connect to Gmail server.

Error: Unsupported AUTHENTICATE mechanism. ub8mb14320060wib. 

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.pyc", line 759, in run
  File "gmv\gmv_cmd.pyc", line 667, in _sync
  File "gmv\gmvault.pyc", line 258, in __init__
  File "gmv\imap_utils.pyc", line 285, in connect
  File "gmv\mod_imap.pyc", line 244, in xoauth_login
  File "imaplib.pyc", line 351, in authenticate
error: Unsupported AUTHENTICATE mechanism. ub8mb14320060wib

=== End of Exception traceback ===

I have also tried the new version v1.9, but in the new version doesn't exist the --2-legged-oauth parameter.

Thank's for your help!

**Comment by gaubert** [comment]
2-legged-oauth doesn't exist anymore (as Oauth1 is gone) to allow syncing for an entire googleapps domain. However there is a way to solve the issue with a private key. I need to implement and test it. I hope to have it done and ready within one to two weeks.

**Comment by danward79** [comment]
Glad that this is not just me ;-)

**Comment by yaroshevych** [comment]
Is there any workaround for this?

**Comment by danward79** [comment]
A work around would be useful, did you find one?

**Comment by gaubert** [comment]
There is no quick work around as I need to implement the access to the
business google apps. I am working on it and will try to release something
fairly quickly.

Guillaume

**Comment by rbrewer** [comment]
One workaround is to use the `--passwd` option, which works with a Google Apps domain on v1.9. Of course this requires that you have the password for the account, which might not be the case in a corporate deployment.

**Comment by danward79** [comment]
Would that work, on a normal google account?

How is the fix coming along?

**Comment by rbrewer** [comment]
@danward79 Not sure if you are asking me or @gaubert, but the `--passwd` flag will let gmvault work with any account that you have the password for: consumer Gmail or Google Apps for Work. I just used it for a Gmail->GAfW account transition, and it worked fine.

**Comment by artooro** [comment]
@gaubert have you been able to get anywhere with the private key authentication method? I need to migrate a few hundred mailboxes from one google apps domain to another and if I could use this that would be perfect.

**Comment by gaubert** [comment]
@danward79 @rbrewer @yaroshevych This is the last thing to tackle in gmv1.9.1 before release.
I will try to work on it in the following weeks.

**Comment by yo-que-se** [comment]
@gaubert have you been able to get anywhere with the private key authentication method?

**Comment by dalin-** [comment]
Upgrading to the latest version (1.9) solved this problem for me.

**Comment by brownrc** [comment]
Is there some documentation on how to use the google apps support for domain wide use? The only thing I see so far is you have to authorize it as each individual user. Was the private key method implemented?

**Comment by shireeshj** [comment]
Has there been any progress on this? I too am looking for a solution where all accounts of an entire Google Apps domain can be backed up. 

I am not a Python programmer, but is there any way I can help in taking this to closure?

**Comment by dalin-** [comment]
@shireeshj I'm pretty sure that this is working in the latest version (unless your google apps is set up differently than mine).

**Comment by dalin-** [comment]
@shireeshj @brownrc 
I suggest opening a new issue, because this one (getting Google Apps to work after the removal of 2-legged-oauth) is solved.  What you're describing seems to be a different (backing up an entire domain).

**Comment by shireeshj** [comment]
you are right. It works for a single google apps account without a hitch. 

I'll log another issue for the domain wide feature. Thanks
