### ISSUE TITLE
Error: 'str' object has no attribute '__exit__' when trying to sync

### ISSUE THREAD

**Issue by robince** [gaubert/gmvault#211]
I get the following error and traceback when trying to sync a gmail account:

    Process email num 7 (imap_id:354617) from 2015-05.
    Error: 'str' object has no attribute '__exit__'.

    === Exception traceback ===
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/gmvault-1.9-py2.6.egg/gmv/gmv_cmd.py", line 741, in run
        self._sync(args, credential)
      File "/usr/lib/python2.6/site-packages/gmvault-1.9-py2.6.egg/gmv/gmv_cmd.py", line 661, in _sync
        restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
      File "/usr/lib/python2.6/site-packages/gmvault-1.9-py2.6.egg/gmv/gmvault.py", line 607, in sync
        self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
      File "/usr/lib/python2.6/site-packages/gmvault-1.9-py2.6.egg/gmv/gmvault.py", line 570, in _sync_emails
        imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
      File "/usr/lib/python2.6/site-packages/gmvault-1.9-py2.6.egg/gmv/gmvault.py", line 528, in _common_sync
        handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
      File "/usr/lib/python2.6/site-packages/gmvault-1.9-py2.6.egg/gmv/gmvault.py", line 154, in handle_sync_imap_error
        raise the_exception
    AttributeError: 'str' object has no attribute '__exit__'

    === End of Exception traceback ===

**Comment by gaubert** [comment]
@robince which version do you use ? 1.9.1 ?
Do you use the encrypt option ?

In any case, set the --debug option and please send me via email the entire console output so that I can understand the source of the problem here.

Thanks

**Comment by robince** [comment]
Thanks, it is version 1.9:
~> gmvault -v
Gmvault v1.9

 I do use the encrypt option. I've sent the debug output in an email.

**Comment by robince** [comment]
I just realised that I was using branch master which is out of date. I didn't realise development was taking place on a separate 1.9.1 branch. With that version it successfully gets past the problem email so I hope the problem is fixed. If so I will close the ticket when the current sync completes.

**Comment by gaubert** [comment]
ok Robin. v1.9.1 is still in test but should be ready within the next two
weeks.
