### ISSUE TITLE
exception when using --store-passwd with 1.9

### ISSUE THREAD

**Issue by gaubert** [gaubert/gmvault#215]
I'm running gmvault v1.9 using the password option (/usr/local/bin/gmvault sync USERNAME@COMAPANYNAME.COM -p --store-passwd

And I'm getting the following error

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9-py2.7.egg/gmv/gmv_cmd.py", line 738, in run
    credential = CredentialHelper.get_credential(args)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9-py2.7.egg/gmv/credential_utils.py", line 199, in get_credential
    passwd = cls.read_password(args['email'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9-py2.7.egg/gmv/credential_utils.py", line 173, in read_password
    cipher       = blowfish.Blowfish(cls.get_secret_key(cls.SECRET_FILEPATH % (gmvault_utils.get_home_dir_path())))
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9-py2.7.egg/gmv/credential_utils.py", line 71, in get_secret_key
    with open(a_filepath).read() as f:
AttributeError: __exit__

=== End of Exception traceback ===

If anyone can offer any help I would greatly appreciate it.  Thanks in advance.

**Comment by gaubert** [comment]
--store-passwd is broken since I had to move to oauth2. I think it isn't supported anymore. I will investigate

**Comment by gaubert** [comment]
ok now when you have activated the two step verification (or even all the time) you cannot use anymore your login/password for gmail. 
You have to generate a password app and use it instead of your password with the options --passwd, --renew-passwd

See for more information:
http://www.howto-outlook.com/news/gmailoauth.htm

and for details on how to generate the passwd apps: https://support.google.com/accounts/answer/185833
