### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by astrofrog** [gaubert/gmvault#221]
At the moment, ``gmvault`` does not run on Python 3:

```python
Traceback (most recent call last):
  File "/tmp/gmvault.bootstrap.63252", line 1, in <module>
    import gmv.gmv_cmd as runner
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/gmv/gmv_cmd.py", line 455
    except Exception, _: #pylint:disable=W0703
                    ^
SyntaxError: invalid syntax
```

I'd be happy to help with supporting Python 3 if needed.

**Comment by gaubert** [comment]
@astrofrog Yes that would be great. Just create your own branch and start transforming the code to make it compliant. This shouldn't be too complex. Then we will have to think about unicode issues.

**Comment by gaubert** [comment]
@astrofrog Did you start working on it ? This is remove most of the unicode issues and that would be great.

**Comment by astrofrog** [comment]
@gaubert I haven't had a chance yet. I will have time again in October to try and work on this, but if anyone else wants to work on this in the mean time, please don't let me stop you! :)

**Comment by paskal** [comment]
I'll try to make it real, seems not a very hard task and I don't want this script to be left only one not supporting 3rd Python.

**Comment by karanrajpal14** [comment]
I'm still facing this issue. Has it been fixed recently @astrofrog ?

**Comment by astrofrog** [comment]
@karanrajpal14 - I haven't had a chance to help with this

**Comment by nestukh** [comment]
Debian Bullseye (next stable release of Debian, probably out later this year) will drop support to Python 2:
https://en.wikipedia.org/wiki/Debian_version_history#Debian_11_(Bullseye)
Pip 21.0 has dropped support for Python 2.7 in January 2021:
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
In fact, you can upgrade `pip` up to version 20.3 and no further in py2 enviroments.
Surely it will be still installable using workarounds, but gmvault is the last program I personally use not yet on 3.
It would be nice to have gmvault on Python 3 too.
I don't have time to contribute, I only know that the utility `2to3` helped me a lot on this matter on various projects.

**Comment by nestukh** [comment]
I've mentioned a workaround in https://github.com/gaubert/gmvault/issues/352#issuecomment-957502832
