### ISSUE TITLE
Type error after 40,000 emails

### ISSUE THREAD

**Issue by mollocon** [gaubert/gmvault#228]
I've gotten about 40,000 emails in and only have 5,000 left, but --resume and --restart keep throwing the same error

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/Molly/anaconda/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 745, in run
    self._restore(args, credential)
  File "/Users/Molly/anaconda/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 621, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/Users/Molly/anaconda/lib/python2.7/site-packages/gmv/gmvault.py", line 882, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/Users/Molly/anaconda/lib/python2.7/site-packages/gmv/gmvault.py", line 1146, in restore_emails
    raise err
TypeError: %d format: a number is required, not set

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know
