### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by lycans15** [gaubert/gmvault#232]
Hello,

Hope you can help me regarding my issue about gmvault, I am now restoring my emails in my back up emails i created but an error occured. "ValueError: No JSON object could be decoded"
Hope you can help me with my problem on how to fix this issue.

This the complete error in terminal.

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 745, in run
    self._restore(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 621, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 882, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 1119, in restore_emails
    handle_restore_imap_error(err, gm_id, db_gmail_ids_info, self)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 84, in handle_restore_imap_error
    raise the_exception
ValueError: No JSON object could be decoded

=== End of Exception traceback ===

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know

**Comment by lycans15** [comment]
Hello, 
Thanks for the reply.
where  can i see the new version of v1.9.1? should i install this new version on my pc if yes, how?

Hope you can help me.
Best Regards,

**Comment by lycans15** [comment]
I already update my current version to v.1.9.1 when i restart or resume to restore my emails it's still they same.

here is the output:

Error: No JSON object could be decoded. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 750, in run
    self._restore(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 625, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 901, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 1145, in restore_emails
    handle_restore_imap_error(err, gm_id, db_gmail_ids_info, self)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 84, in handle_restore_imap_error
    raise the_exception
ValueError: No JSON object could be decoded

=== End of Exception traceback ===

**Comment by gaubert** [comment]
It looks like your have some corrupted or mission JSON object (.meta files) in the gmvault database dir.

You might have to delete the wrong JSON object. Do you used a network based disk service (like dropbox or a SAN ?)
I would redo a clean restore or a non network based network and restore that one.

Let me know how it go

**Comment by lycans15** [comment]
Hello,
I don't used a network based disk service. How to fix this? 

thanks

**Comment by gaubert** [comment]
@lycans15 there was a disk corruption somehow. Go the gmvault-db dir and delete the email eml.gz and .meta file for the failing email. It should be called id.eml.gz and id.meta with the id equal to something like 1150827300..etc.meta
