### ISSUE TITLE
UnboundLocalError: local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by johndangerstorey** [gaubert/gmvault#234]
I just downloaded and implemented version 1.9.1 of gmvault and it's giving me a very similar error referenced in issue (https://github.com/gaubert/gmvault/issues/199) - I left this same question here but because the issue was "closed" i'm guessing it isn't checked anymore.  Regardless, here is the output:

Pushing email body with id 1414150177260942940.
Error: local variable 'res' referenced before assignment.

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 750, in run
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 625, in _restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 901, in restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 1142, in restore_emails
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 84, in handle_restore_imap_error
UnboundLocalError: local variable 'res' referenced before assignment

=== End of Exception traceback ===

Any ideas?

**Comment by gaubert** [comment]
normally fixed in v1.9.2 to be released
