### ISSUE TITLE
Need gmvault latest version for windows os. 9.1 version gets terminated in between

### ISSUE THREAD

**Issue by Gmail2016** [gaubert/gmvault#238]
Please help me. I am getting the error below. I downloaded the 9.1 version, I was able to restore a few emails but then have been getting this error. I need to restore my emails in 2 days as my office wants to reformat all computers and after reformatting I do not know if I'll be able to save the gmvault files. I am using a windows OS.

![image](https://cloud.githubusercontent.com/assets/16752052/12638454/501fd0d6-c5c3-11e5-9343-44ad11e79684.png)

**Comment by Gmail2016** [comment]
#217 - please give solutions

**Comment by gaubert** [comment]
Check the new version v1.9.1 as the problem should have been fixed. Let me know

**Comment by ikhwani** [comment]
Hi gaubert,

I am having the same issue with version 1.9.1 on Ubuntu.

```
Pushing email body with id 1480670529217782369.
Pushing email body with id 1480671119189956584.
Pushing email body with id 1480671235149967146.
Error: argument of type 'NoneType' is not iterable. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 750, in run
    self._restore(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 625, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 901, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 1145, in restore_emails
    handle_restore_imap_error(err, gm_id, db_gmail_ids_info, self)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 84, in handle_restore_imap_error
    raise the_exception
TypeError: argument of type 'NoneType' is not iterable

=== End of Exception traceback ===
```

**Comment by gaubert** [comment]
Could you re-run the same command with --debug and post the entire console
output.
It looks like you both have a corrupted metadata file

**Comment by ikhwani** [comment]
It doesn't always fail at the same message. If I run the restore command again, it will continue & successfully process the previously failed message. But at some point at another message it will stop again with the same exception.

Here is the debug output:
```
Unbury email with gm_id 1485093891580673379.
Pushing email body with id 1485093891580673379.
Subject = Permintaan kamar periode 28-29 Desember 2014/ 1 HARRIS Room.
Before to Append email contents
Appended data with flags [u'\\Seen'] and internal time 2014-11-18 07:31:42. Operation time = 0.980437040329.
res = [APPENDUID 11 61114] (Success)

result_uid = 61114
label = \Inbox

label = \Important

Unbury email with gm_id 1485094052596848856.
Pushing email body with id 1485094052596848856.
Subject = RE: Room 31 dec 1 night only.
Before to Append email contents
Appended data with flags [u'\\Seen'] and internal time 2014-11-18 07:34:15. Operation time = 2.84594202042.
res = None

Catch the following exception argument of type 'NoneType' is not iterable
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 1119, in restore_emails
    email_meta[self.gstorer.INT_DATE_K] )
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/imap_utils.py", line 132, in wrapper
    return the_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/imap_utils.py", line 815, in push_data
    if '(Success)' not in res:
TypeError: argument of type 'NoneType' is not iterable
Error: argument of type 'NoneType' is not iterable. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 750, in run
    self._restore(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 625, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 901, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 1145, in restore_emails
    handle_restore_imap_error(err, gm_id, db_gmail_ids_info, self)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 84, in handle_restore_imap_error
    raise the_exception
TypeError: argument of type 'NoneType' is not iterable

=== End of Exception traceback ===
```

**Comment by migueldeicaza** [comment]
I am experiencing a similar issue, here is the  relevant part of the log:

```
Unbury email with gm_id 1533137459543042798.
Pushing email body with id 1533137459543042798.
Subject = XamProud.
Before to Append email contents
Appended data with flags [u'\\Seen'] and internal time 2016-05-01 10:43:37. Operation time = 0.711796998978.
res = None

Catch the following exception argument of type 'NoneType' is not iterable
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 1119, in restore_emails
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.imap_utils", line 132, in wrapper
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.imap_utils", line 815, in push_data
TypeError: argument of type 'NoneType' is not iterable
Error: argument of type 'NoneType' is not iterable. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 750, in run
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 640, in _restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 901, in restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 1145, in restore_emails
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 84, in handle_restore_imap_error
TypeError: argument of type 'NoneType' is not iterable

=== End of Exception traceback ===
```

**Comment by tmancill** [comment]
I am running version 1.9.1 on Debian and seeing this same error as well at seemingly random points during an attempted restore.  The first run died after pushing 1239 messages, then 129, then 4256.  I checked the metadata for the last message id displayed and it looked fine.  I believe the problem is pointed out in the debug provided by @ikhwani:

> Appended data with flags [u'\\Seen'] and internal time 2014-11-18 07:34:15. Operation time = 2.84594202042.
> **res = None**

If the code falls through [this test](https://github.com/gaubert/gmvault/blob/master/src/gmv/imap_utils.py#L805), `res` won't be set and result in the exception being thrown [here](https://github.com/gaubert/gmvault/blob/master/src/gmv/imap_utils.py#L815).

If I can get it working better, I'll submit a patch.

**Comment by joh1234** [comment]
Great, thanks. https://goo.gl/JBljdR
