### ISSUE TITLE
unable python setup.py install or pip install gmvault in ubuntu linux

### ISSUE THREAD

**Issue by mustart** [gaubert/gmvault#243]
I Cannot found linux binary for ubuntu as the src throught download page v1.9 README.txt referred.
It took some hard hours to install, because "python setup.py install" encounted error:
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup
ImportError: No module named setuptools

I have Python 2.7.9 (default, May 23 2015, 08:44:49) 
[GCC 4.6.3] on linux2
My OS is Ubuntu 12.04 LTS.
and have python-setuptools as current compatibility packages v0.6.24-1ubuntu1

Later "pip install gmvault" seemed success. In spite of I got gmvault in /usr/local/bin, it cannot run  gmvault -h
Traceback (most recent call last):
  File "/tmp/gmvault.bootstrap.10464", line 1, in <module>
    import gmv.gmv_cmd as runner
ImportError: No module named gmv.gmv_cmd

I read similar in this github dated in 2012, but solved in a way using python 2.6, but this version does not exists in my machine and not found anyway.
Can You help me?

**Comment by gaubert** [comment]
ok I need to make a test on ubuntu to see what is available

**Comment by wsw70** [comment]
The same issue exists on Ubuntu 16.10 (xenial) with Python 3.5 and an install via `pip` (`gmvault` version 1.9.1).

**Comment by tmancill** [comment]
I ran into the error `ImportError: No module named setuptools` on Ubuntu 16.04 LTS, but was easily able to get around it by installing the `python-setuptools` package:

    sudo apt-get install python-setuptools

And then running the install:

    sudo python setup.py install

After which `gmvault -h` and `gmvault -v` are healthy save for the [harmless warning](https://github.com/gaubert/gmvault/blob/master/etc/scripts/gmvault#L63):  *Odd. Use default python2.7.x or 2.6.x _distribution.*

**Comment by sorokod** [comment]
At the very least, a documentation bug. See http://gmvault.org/install.html#install , "Python Source Installation"

**Comment by joh1234** [comment]
Great, thanks. https://goo.gl/JBljdR

**Comment by gaubert** [comment]
@sorokod version 1.9.2-beta-1 available for test and fixing many additional problems (especially in the restore). Please test it and let me know if this is fine within 6 days. Many thanks.

https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0

**Comment by erichuang** [comment]
v1.9.2b1 still doesn't seem to work, on Mac at least

**Comment by mustart** [comment]
Please give me extra time or new beta version.

Musulin, Béla
---

2017-02-12 14:33 GMT+01:00 Guillaume Aubert <notifications@github.com>:
