### ISSUE TITLE
GMVault behind a proxy

### ISSUE THREAD

**Issue by niawag** [gaubert/gmvault#247]
Hi, I'm trying to set up GMVault on a Synology NAS behind a proxy.
The Auth part worked without a problem but it won't sync and returns this error: 

```
./gmvault sync mygmailadress@gmail.com

Use gmvault-db located in /var/services/homes/____/gmvault-db.

Activate Gmvault db cleaning.
Create defaults in /var/services/homes/___/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from /var/services/homes/___/.gmvault/mygmailadress@gmail.com.oauth2.

Connect to Gmail server.

Error: Network problem. Please check your gmail server hostname, the internet connection or your network setup.

=== Exception traceback ===
Traceback (most recent call last):
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 658, in _sync
    use_encryption = args['encrypt'])
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/gmv/gmvault.py", line 258, in __init__
    self.src.connect()
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/gmv/imap_utils.py", line 290, in connect
    self.server = mimap.MonkeyIMAPClient(self.host, port = self.port, use_uid= self.use_uid, need_ssl= self.ssl)
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/gmv/mod_imap.py", line 248, in __init__
    super(MonkeyIMAPClient, self).__init__(host, port, use_uid, need_ssl)
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/imapclient/imapclient.py", line 146, in __init__
    self._imap = self._create_IMAP4(**kwargs)
  File "/volume1/homes/___/GMVault/gmvault_env/lib/python2.7/site-packages/imapclient/imapclient.py", line 155, in _create_IMAP4
    return ImapClass(self.host, self.port, **kwargs)
  File "/usr/lib64/python2.7/imaplib.py", line 1166, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib64/python2.7/imaplib.py", line 173, in __init__
    self.open(host, port)
  File "/usr/lib64/python2.7/imaplib.py", line 1177, in open
    self.sock = socket.create_connection((host, port))
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 101] Network is unreachable
```

Is there a way to make GMVault work behind a proxy?

**Comment by weakish** [comment]
gmvault works with proxychains.

**Comment by niawag** [comment]
Ok, I'll try that, thanks for your help!

**Comment by gaubert** [comment]
You have to setup the proxy externally and it will work.
