### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by endolith** [gaubert/gmvault#248]
2 accounts synced successfully, but the other keeps failing with the error 

```
=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 665, in _sync
    restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 626, in sync
    self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 589, in _sync_emails
    imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 547, in _common_sync
    handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 154, in handle_sync_imap_error
    raise the_exception
IOError: [Errno 2] No such file or directory: '/mnt/drivepool/GMVault/db/2008-01/1258031168566452298.meta'

=== End of Exception traceback ===
```

Shouldn't it create any folders or files it needs?

```
 ~> gmvault --version
Odd. Use default python2.7.x or 2.6.x distribution.

Gmvault v1.9.1
```

**Comment by endolith** [comment]
There was a `1258031168566452298.eml.gz` file though.  I deleted it but that didn't help.

**Comment by gaubert** [comment]
@endolith For some reasons, the meta file for that email has disappeared or was not properly created. I will handle that error by ignoring that email (moving it to quarantine or deleting it ?, let's see). This will be in v1.9.2

**Comment by gaubert** [comment]
@endolith  you can test the latest beta version here (beta windows and mac os x package available):
https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0

or from the branch gmv-1.9.2

Help required for testing to see if I missed something. Many thanks for the testing.

**Comment by gaubert** [comment]
@endolith version 1.9.2-beta-1 available for test and fixing many additional problems (especially in the restore). Please test it and let me know if this is fine within 6 days. Many thanks.

https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0

**Comment by endolith** [comment]
I'm not sure how to install this on Ubuntu.  I cloned the repo:

```
~/P/gmvault> git status
On branch gmv-1.9.2
Your branch is up-to-date with 'origin/gmv-1.9.2'.
nothing to commit, working directory clean
```

and then tried 

```
~/P/gmvault> sudo pip install --upgrade .

...

    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Q_sDiH/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zdt3mE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Q_sDiH/cryptography/
```

**Comment by gaubert** [comment]
@endolith for the moment I have not push the new version to pip. It is still being tested.
Best is to pull the branch gmv-1.9.2 
`$>cd gmvault
$> make gmv-pypi-dist
....
$>cd build ; tar zxvf gmvault-1.9.2-beta-1.tar.gz
$>cd gmvault-1.9.2-beta1
$>python setup.py install`

If I didn't make any typo, it should then allow you to install the latest version for testing.

It also seems that you need to install the ssl-devel packages as you need to compile some ssl parts for the underlined used imap library.
Hope I was clear

**Comment by endolith** [comment]
With `gmvault-1.9.2b1.tar.gz` and `libssl-dev` and after uninstalling gmvault and reinstalling with setup.py it seems to have worked.

```
~> gmvault -v
Odd. Use default python2.7.x or 2.6.x distribution.

Gmvault v1.9.2-beta-1
```

I'll set it up with my accounts and try again.

**Comment by endolith** [comment]
```
Connect to Gmail server.

Error: 'module' object has no attribute 'create_default_context'. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.2b1-py2.7.egg/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.2b1-py2.7.egg/gmv/gmv_cmd.py", line 658, in _sync
    use_encryption = args['encrypt'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.2b1-py2.7.egg/gmv/gmvault.py", line 258, in __init__
    self.src.connect()
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.2b1-py2.7.egg/gmv/imap_utils.py", line 306, in connect
    context = imapclient.create_default_context(cafile= gmvault_utils.get_ca_certs_filepath())
AttributeError: 'module' object has no attribute 'create_default_context'

=== End of Exception traceback ===
```
