### ISSUE TITLE
Consistently get "Error: Lookup failed" message.

### ISSUE THREAD

**Issue by jasonanovak** [gaubert/gmvault#253]
I had been using gmvault successfully with my gmail account on a different computer.  I changed computers, and I installed gmvault on it using pip, and then tried to run a full gmvault sync to bring my gmail hosted account down to that computer.

I successfully get the OAUTH token for my 2FA account through the gmail interface, but I consistently get the following error message when I try to sync:

Connect to Gmail server.

Error: Lookup failed b17mb443604527ign.

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmv_cmd.py", line 658, in _sync
    use_encryption = args['encrypt'])
  File "/usr/local/lib/python2.7/dist-packages/gmv/gmvault.py", line 258, in __init__
    self.src.connect()
  File "/usr/local/lib/python2.7/dist-packages/gmv/imap_utils.py", line 301, in connect
    self.server.oauth2_login(self.credential['value'])
  File "/usr/local/lib/python2.7/dist-packages/gmv/mod_imap.py", line 256, in oauth2_login
    typ, data = self._imap.authenticate('XOAUTH2', lambda x: oauth2_cred)
  File "/usr/lib/python2.7/imaplib.py", line 363, in authenticate
    raise self.error(dat[-1])
error: Lookup failed b17mb443604527ign

Is there any additional logging I can provide?

**Comment by jasonanovak** [comment]
Never mind, figured out the error.

**Comment by krainboltgreene** [comment]
Why not tell people the fix?!

**Comment by spinegar** [comment]
What was the fix?

**Comment by flop25** [comment]
agree! I'm on the 1.9.2 beta from https://github.com/gaubert/gmvault/issues/285#issuecomment-277521706 and got that!

**Comment by joolsa** [comment]
Thanks! I had the same problem, make sure you have the email without quotes ('me@gmail.com' --> me@gmail.com).
