### ISSUE TITLE
Error: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by sonisharma** [gaubert/gmvault#256]
Hi,
I have been getting the following error message repeatedly when I try to restore my email to a new email account:

Error: argument of type 'NoneType' is not iterable.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 750, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 625, in _restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 901, in restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 1145, in restore_emails
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 84, in handle_restore_imap_error
TypeError: argument of type 'NoneType' is not iterable

=== End of Exception traceback ===

I tried restoring the email from my original account again by deleting but still get this error. Any idea what's going wrong?

**Comment by tmancill** [comment]
Hi @sonisharma .  I was running into the same problem because the IMAP utility class wasn't retrying when the result returned is `None`.  The patch in PR #255 resolved the issue for me.

**Comment by gaubert** [comment]
fixed in v1.9.2. See #281
