### ISSUE TITLE
Restore fails with "Error: create failed: '[CANNOT] No folder name given. (Failure)'. "

### ISSUE THREAD

**Issue by patrickboeert** [gaubert/gmvault#259]
I am restoring into Gmail, after backing up from Google Apps.

`./gmvault restore -d ~/gmvault-db first.last@gmail.com --resume`

fails after pushing about 40 emails with

```
Error: create failed: '[CANNOT] No folder name given. (Failure)'. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 750, in run
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 625, in _restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 901, in restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 1150, in restore_emails
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.imap_utils", line 622, in create_gmail_labels
error: create failed: '[CANNOT] No folder name given. (Failure)'

=== End of Exception traceback ===

```

What did I do wrong?

**Comment by gaubert** [comment]
@patrickboeert You seem to have a label name that is not valid. I would need to check the labels of the email failing to be pushed.
Could you re-run the smae command with --debug 

`./gmvault restore -d ~/gmvault-db first.last@gmail.com --resume --debug`

and send me the gmvault.log file created in your $HOME directory (on a MAC /Users/myuser.
Please send it to me via email.

Thks

**Comment by saeckry** [comment]
Hello, I do not mean to steal this bug thread but I have the same issue and noticed this bug report hasn't been resolved, so I have sent an email with the debug log just now to you.

Thanks in advance!
