### ISSUE TITLE
Problem with the v1.8.1-beta version

### ISSUE THREAD

**Issue by Aydenkeller** [gaubert/gmvault#260]
Hi,

I've tried installing and launching Gmvault v1.9.1 on my MacBook but it didn't work (no /bin folder), so I downloaded the v1.8.1-beta version.

I wish to back up my Gmail inbox onto an external hard drive, so I've downloaded and unzipped the file exactly where I wish the data to be, and then I used to Terminal to position myself at that place too.

After going to the /bin directory and typing "./gmvault sync t.aydenkeller@gmail.com" from there, this is what I get:

"
Use gmvault-db located in /Users/arthur/gmvault-db.

Activate Gmvault db cleaning.
Create defaults in /Users/arthur/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Authentication performed with Gmail XOAuth token.

Initiate interactive session to get XOAuth normal or 2-legged token from Gmail.

Received Error: {'status': 302, 'body': '<HTML>\n<HEAD>\n<TITLE>Moved Temporarily</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Moved Temporarily</H1>\nThe document has moved <A HREF="https://accounts.google.com/OAuthGetRequestToken?oauth_nonce=83830426&amp;oauth_timestamp=1477180780&amp;oauth_consumer_key=anonymous&amp;oauth_signature_method=HMAC-SHA1&amp;xoauth_displayname=Gmvault+-+Backup+your+Gmail+account&amp;oauth_version=1.0&amp;scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo%23email&amp;oauth_signature=DBo6mwEbXvU913kah0A0e8sRonI%3D">here</A>.\n</BODY>\n</HTML>\n', 'reason': 'Non 200 response on fetch request token'}.

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv/credential_utils.pyc", line 68, in get_oauth_tok_sec
  File "gdata/service.pyc", line 429, in FetchOAuthRequestToken
FetchingOAuthRequestTokenFailed: {'status': 302, 'body': '<HTML>\n<HEAD>\n<TITLE>Moved Temporarily</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Moved Temporarily</H1>\nThe document has moved <A HREF="https://accounts.google.com/OAuthGetRequestToken?oauth_nonce=83830426&amp;oauth_timestamp=1477180780&amp;oauth_consumer_key=anonymous&amp;oauth_signature_method=HMAC-SHA1&amp;xoauth_displayname=Gmvault+-+Backup+your+Gmail+account&amp;oauth_version=1.0&amp;scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo%23email&amp;oauth_signature=DBo6mwEbXvU913kah0A0e8sRonI%3D">here</A>.\n</BODY>\n</HTML>\n', 'reason': 'Non 200 response on fetch request token'}

=== End of Exception traceback ===

Error: need more than 2 values to unpack. 

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv/gmv_cmd.pyc", line 755, in run
  File "gmv/credential_utils.pyc", line 343, in get_credential
ValueError: need more than 2 values to unpack

=== End of Exception traceback ===
"

Please help! This is language from outer space for me...

Thanks very much in advance,

Tristan

**Comment by gaubert** [comment]
Need to check if v1.9.1 is working on a recent Mac

**Comment by gaubert** [comment]
ok @Aydenkeller I did a quick test with gmvault 1.9.1 from the download area and it works. Ignore v1.8.2 as it will never work since Gmail has changed is way to authenticate.

Here is what you have to do. Open a terminal in Applications/Utilies/Term

> 
$>wget https://bitbucket.org/gaubert/gmvault-official-download/downloads/gmvault-v1.9.1-macosx-intel.tar.gz
HTTP request sent, awaiting response... 200 OK
Length: 5659518 (5.4M) [application/x-tar]
Saving to: ‘gmvault-v1.9.1-macosx-intel.tar.gz’
2017-01-03 17:22:48 (2.11 MB/s) - ‘gmvault-v1.9.1-macosx-intel.tar.gz’ saved [5659518/5659518]`
$>tar zxvf gmvault-v1.9.1-macosx-intel.tar.gz
$>cd gmvault-v.1.9.1
$>./gmvault sync myemail@gmail.com 
> 
Then your syncing should start.

Let me know how it goes.
