### ISSUE TITLE
Error: Cannot find global 'Drafts' folder..

### ISSUE THREAD

**Issue by jc21** [gaubert/gmvault#272]
```bash
Connect to Gmail server.

Error: Cannot find global 'Drafts' folder..

=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/usr/lib/python2.6/site-packages/gmv/gmv_cmd.py", line 658, in _sync
    use_encryption = args['encrypt'])
  File "/usr/lib/python2.6/site-packages/gmv/gmvault.py", line 258, in __init__
    self.src.connect()
  File "/usr/lib/python2.6/site-packages/gmv/imap_utils.py", line 313, in connect
    self.find_folder_names()
  File "/usr/lib/python2.6/site-packages/gmv/imap_utils.py", line 132, in wrapper
    return the_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/gmv/imap_utils.py", line 381, in find_folder_names
    raise Exception("Cannot find global 'Drafts' folder.")
Exception: Cannot find global 'Drafts' folder.

=== End of Exception traceback ===
```

This is a google apps account.

I do indeed have a "Drafts" folder in the list in my Gmail account, however the filter displayed for it is "in:draft" so I'm pretty sure this check needs to include "draft" as well as "Drafts", if it's even needed at all.

In any case, I can't use gmvault due to this.

**Comment by sannysoft** [comment]
I have the same issue. Please help

**Comment by robertmhoehn** [comment]
I have the same issue.
