### ISSUE TITLE
Error: argument of type 'NoneType' is not iterable.

### ISSUE THREAD

**Issue by LPHebert** [gaubert/gmvault#281]
1- Gmvault v1.9.1
2- Windows 7 Professional
3- Bug

== Processed 2640 emails in 1h 17m 2s. 3363 left to be restored (time estimate 1h 38m 8s). ==

Processing next batch of 80 emails.

...
Pushing email body with id 1519476572414769630.
Error: argument of type 'NoneType' is not iterable.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 750, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 625, in _restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 901, in restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 1145, in restore_emails
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 84, in handle_restore_imap_error
TypeError: argument of type 'NoneType' is not iterable

=== End of Exception traceback ===

4- Don't know how to reproduce the error
5- LouisPaulHebert@gmail.com

**Comment by ashikul** [comment]
Os9kZOOoss9999999ss

**Comment by gaubert** [comment]
Ok it should be fixed in v1.9.2. This means that there was an error while restoring an email (bad email) and somehow the GMAIL IMAP response was incorrect. Try to handle that now.
