### ISSUE TITLE
IMAPClient requires higher version?

### ISSUE THREAD

**Issue by atppp** [gaubert/gmvault#289]
On branch gmv-1.9.2, When I test with "python install.py setup" or with the binary built by "make gmv-mac-dist", I got the following error. The fix is to change IMAPClient version from 0.13 to 1.0.2 as noted at https://github.com/atppp/gmvault/commit/6b2660a93f6367b269ad5db823032d66b33ef5e2

...
Connect to Gmail server.

Error: 'module' object has no attribute 'create_default_context'. 

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv/gmv_cmd.py", line 746, in run
  File "gmv/gmv_cmd.py", line 658, in _sync
  File "gmv/gmvault.py", line 258, in __init__
  File "gmv/imap_utils.py", line 306, in connect
AttributeError: 'module' object has no attribute 'create_default_context'

=== End of Exception traceback ===

**Comment by gaubert** [comment]
Of course you need the last imap client version. I will update the setup.py. The issue should be different with the exe because in there you have the latest version embedded.

**Comment by gaubert** [comment]
@atppp  you can test the latest beta version here (beta windows and mac os x package available):
https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0

or from the branch gmv-1.9.2

Help required for testing to see if I missed something. Many thanks for the testing.

**Comment by gaubert** [comment]
@atppp version 1.9.2-beta-1 available for test and fixing many additional problems (especially in the restore). Please test it and let me know if this is fine within 6 days. Many thanks.

https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0
