### ISSUE TITLE
1.9.2 (Beta) Cannot reach gmail server & Exception traceback errors

### ISSUE THREAD

**Issue by newuser2017** [gaubert/gmvault#293]
Hi, 

First post, and not a developer/coder so apologies if I'm not displaying all the right information.

In the middle of restoring a google apps domain email account (i.e. xxx@companyname.com as opposed to a gmail account) I received the following error

`Error: argument of type 'NoneType' is not iterable.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 750, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 625, in _restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 901, in restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 1145, in restore_emails
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 84, in handle_restore_imap_error
TypeError: argument of type 'NoneType' is not iterable

=== End of Exception traceback ===`

Having googled it, I saw that this a few users had this issue and that it was supposed to be fixed for 1.9.2.

I downloaded the beta version and ran gmvault restore xxx@xxxx.com --resume and got the following error.

gmvault-shell>gmvault restore XXXXXXXXXX@gmail.com --resume

Use gmvault-db located in C:\Users\XXXXXXXX/gmvault-db.

Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from C:\Users\XXXXXXX/.gmvault/lXXXXXXXXXX@gmail.com.oauth2.

Connect to Gmail server.

Start restoration (2017-02-16T08h43m24s).

Start emails restoration.

Restore emails in gmail account XXXXXXXXp@gmail.com.
Read email info from C:\Users\lXXXXXXXXXX/gmvault-db gmvault-db.
Total number of elements to restore 75869.
Restart from gmail id 1474955902712634530.
Got all emails id left to restore. Still 61949 emails to do.

Processing next batch of 80 emails.

Pushing email body with id 1474956215852152885.
Pushing email body with id 1474956802760440965.
Pushing email body with id 1474956903184209990.
Pushing email body with id 1474957023999391585.
Pushing email body with id 1474957291355749269.
Pushing email body with id 1474957312244958153.
Pushing email body with id 1474957340195339184.
Pushing email body with id 1474957603960795141.
Pushing email body with id 1474957843310332625.
Pushing email body with id 1474957925826560604.
Pushing email body with id 1474958611774517938.
Pushing email body with id 1474958834069578758.
Pushing email body with id 1474959457432173475.
Pushing email body with id 1474959783373431135.
Pushing email body with id 1474959890959359241.
Pushing email body with id 1474960855781714519.
Pushing email body with id 1474960878366148227.
Pushing email body with id 1474961353349880680.
Pushing email body with id 1474961374186374623.
Pushing email body with id 1474961396276731000.
Pushing email body with id 1474961593380494155.
Pushing email body with id 1474961738800247536.
Pushing email body with id 1474961755631438299.
Pushing email body with id 1474961788282756213.
Pushing email body with id 1474961981830825604.
Pushing email body with id 1474962084355379311.
Pushing email body with id 1474962833725495793.
Pushing email body with id 1474963228534200715.
Pushing email body with id 1474963486124902098.
Pushing email body with id 1474963610785591708.
Pushing email body with id 1474963978909617300.
Pushing email body with id 1474964478708288499.
Pushing email body with id 1474965006523741863.
Cannot reach the Gmail server. Wait 1 second(s) and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from C:\Users\XXXXXX/.gmvault/XXXXXXXXp@gmail.com.oauth2.

Cannot reach the Gmail server. Wait 2 second(s) and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from C:\Users\XXXXXXXXXXXg/.gmvault/XXXXXXXXXp@gmail.com.oauth2.

Cannot reach the Gmail server. Wait 4 second(s) and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from C:\Users\XXXXXXXX/.gmvault/lXXXXXXXXX@gmail.com.oauth2.

Cannot reach the Gmail server. Wait 8 second(s) and retrying.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from C:\Users\XXXXXXXXX/.gmvault/XXXXXXXX@gmail.com.oauth2.

Stop retrying, tried too many times ...
Error: GIMAPFetcher cannot restore email in XXXXXXXXXXXX@gmail.com account..

=== Exception traceback ===
Traceback (most recent call last):
  File "gmv\gmv_cmd.py", line 750, in run
  File "gmv\gmv_cmd.py", line 625, in _restore
  File "gmv\gmvault.py", line 902, in restore
  File "gmv\gmvault.py", line 1146, in restore_emails
  File "gmv\gmvault.py", line 80, in handle_restore_imap_error
PushEmailError: GIMAPFetcher cannot restore email in XXXXXxxXX@gmail.com account.

=== End of Exception traceback ===

gmvault-shell>Error: argument of type 'NoneType' is not iterable.
'Error:' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>
gmvault-shell>=== Exception traceback ===
'Exception' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>Traceback (most recent call last):
'Traceback' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 750, in run
'File' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 625, in _restore
'File' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 901, in restore
'File' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 1145, in restore_emails
'File' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 84, in handle_restore_imap_error
'File' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>TypeError: argument of type 'NoneType' is not iterable
'TypeError:' is not recognized as an internal or external command,
operable program or batch file.

gmvault-shell>
gmvault-shell>=== End of Exception traceback ===

I have looked to use gmvault on three different machines backing up three different accounts and all got the same error in gmvault version 1.9.1 - I'll happily donate to the program once I get all e-mails fully restored.

Thanks in advance,

**Comment by gaubert** [comment]
@newuser2017 Ok thanks I found another potential issue when the metadata is not correctly written. I will regenerate a version for testing for you and let you know soon.

**Comment by mcredskins28** [comment]
Has this been fixed? Where do I download the beta from?

**Comment by emanuelelaface** [comment]
I have the same issue, was it fixed somewhere?

**Comment by sigul** [comment]
same

**Comment by choicepunk** [comment]
I'm also looking for this solution.

**Comment by kanted1** [comment]
@gaubert struck at the same point
![image](https://user-images.githubusercontent.com/12494911/56186319-af7cb280-603c-11e9-9565-4a4df3bd166c.png)
