### ISSUE TITLE
Error in the sync after all emails have been downloaded

### ISSUE THREAD

**Issue by Chachni** [gaubert/gmvault#296]
Hi,
When i run:
gmvault sync -d /database_folder/ xyz@gmail.com

I get the following error after all the emails have been downloaded:

> Read all gmail ids from the Gmvault db. It might take a bit of time ...
> 
> Error: invalid literal for long() with base 10: '1442560994134946382 [conflicted]'.
> 
> === Exception traceback ===
> Traceback (most recent call last):
>   File "/home/xyz/programs/anaconda3/envs/gmvault_env/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 746, in run
>     self._sync(args, credential)
>   File "/home/xyz/programs/anaconda3/envs/gmvault_env/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 665, in _sync
>     restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
>   File "/home/xyz/programs/anaconda3/envs/gmvault_env/lib/python2.7/site-packages/gmv/gmvault.py", line 638, in sync
>     self.check_clean_db(db_cleaning)
>   File "/home/xyz/programs/anaconda3/envs/gmvault_env/lib/python2.7/site-packages/gmv/gmvault.py", line 765, in check_clean_db
>     db_gmail_ids_info = self.gstorer.get_all_existing_gmail_ids()
>   File "/home/xyz/programs/anaconda3/envs/gmvault_env/lib/python2.7/site-packages/gmv/gmvault_db.py", line 346, in get_all_existing_gmail_ids
>     gmail_ids[long(os.path.splitext(fname)[0])] = os.path.basename(directory)
> ValueError: invalid literal for long() with base 10: '1442560994134946382 [conflicted]'
> 
> === End of Exception traceback ===
> 

I have installed gmvault in a separate environment in anaconda. Here are the packages in that environment:

> packages in environment at /home/xyz/programs/anaconda3/envs/gmvault_env:
>
> argparse                  1.4.0                     <pip>
> chardet                   2.3.0                     <pip>
> gmvault                   1.9.1                     <pip>
> IMAPClient                0.13                      <pip>
> Logbook                   0.10.1                    <pip>
> openssl                   1.0.2k                        0
> pip                       9.0.1                    py27_1
> python                    2.7.13                        0
> readline                  6.2                           2
> setuptools                27.2.0                   py27_0
> six                       1.10.0                    <pip>
> sqlite                    3.13.0                        0
> tk                        8.5.18                        0
> wheel                     0.29.0                   py27_0
> zlib                      1.2.8                         3 

In the beginning i didn't have that problem. Just started some weeks ago. Any ideas?
Thanks!

**Comment by Chachni** [comment]
Just for update: in the end i just rerun the full sync with a new database folder, and all worked fine.
