### ISSUE TITLE
Cannot restore - Flag problem

### ISSUE THREAD

**Issue by somnius80** [gaubert/gmvault#317]
Hi! I´m trying to restore a dB synched from one account to another. The process gets interrupted after a few emails. I have been looking into the emails meta files, and it seems only emails with flag other than "\Seen" are generating the error.

Example meta file with restore interruption:
{"thread_ids": 1300507201860545565, "msg_id": "006d01c9bfdc$eb12fbd0$1101a8c0@Ricardo", "flags": [**90040**, "\\Seen"], "gm_id": 1300507201860545565, "internal_date": 1240249516, "x_gmail_received": null, "labels": ["\\Sent"], "subject": xxxyyyzzz"}

I really don't care about the flag being restored. It dates back to when I used Outlook as email client, which I no longer use. Is there a way to bypass flag restoration?

My system is Windows 8.1. Gmvault version is 1.9.1.

**Here is the gmvault command and output:**

gmvault-shell>gmvault_ restore -d "c:\temp\gmvault\mydir" myemail@mydomain.com

Use gmvault-db located in c:\temp\gmvault\mydir.

Create defaults in C:\Users\admin/.gmvault/gmvault_defaults.conf. Please touch this file only if you know what to do.
Authentication performed with Gmail OAuth2 access token.

Get OAuth2 credential from C:\Users\admin/.gmvault/myemail@mydomain.com.oauth2.

Connect to Gmail server.

Start restoration (2017-12-21T11h09m08s).

Start emails restoration.

Restore emails in gmail account myemail@mydomain.com.
Read email info from c:\temp\gmvault\mydir gmvault-db.
Total number of elements to restore 21467.
Got all emails id left to restore. Still 21467 emails to do.

Processing next batch of 80 emails.

Pushing email body with id 1285986936573055642.
Pushing email body with id 1286157780300662756.
Pushing email body with id 1286161526362722884.
Pushing email body with id 1286722537772497399.
Pushing email body with id 1286796224674370395.
Pushing email body with id 1286811802770819883.
Pushing email body with id 1286821965261545504.
Pushing email body with id 1286824554513677940.
Pushing email body with id 1300139494268056015.
Pushing email body with id 1300221957320867145.
Pushing email body with id 1300230009919385480.
Pushing email body with id 1300236017047541706.
Pushing email body with id 1300238884732109045.
Pushing email body with id 1300507201860545565.
Error: sequence item 0: expected string or Unicode, int found.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 750, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 625, in _restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 901, in restore
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 1145, in restore_emails
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmvault", line 84, in handle_restore_imap_error
TypeError: sequence item 0: expected string or Unicode, int found

=== End of Exception traceback ===

**Comment by somnius80** [comment]
Well, given that there was no answer whatsoever, and that I lack knowledge on Python, I built my own application in C language to remove the flags from those emails. It is rather fast. If anyone has a similar issue and wants the Source Code, here it is:

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>

#define DIR_SIZE 256
#define FILE_SIZE 512

int main(int c, char *args[]) {
    printf("Remove Flags from emails for GMVault restoration.\n");

    char * mainDir, * subDir, * subDirFullPath, * fileName, * fileFullPath, * fileText, * cropRoot, * cropTail;
    char fileChar;
    struct dirent *pDirent, *pSubDirent;
    DIR *pDir, *pSubDir;
    FILE *pFile;

    //initialization
    mainDir = malloc(DIR_SIZE); mainDir[0] = '\0';
    subDir = malloc(DIR_SIZE); subDir[0] = '\0';
    subDirFullPath = malloc(DIR_SIZE); subDirFullPath[0] = '\0';
    fileName = malloc(DIR_SIZE); fileName[0] = '\0';
    fileFullPath = malloc(DIR_SIZE); fileFullPath[0] = '\0';
    fileText = malloc(FILE_SIZE); fileText[0] = '\0';
    cropRoot = malloc(FILE_SIZE); cropRoot[0] = '\0';
    cropTail = malloc(FILE_SIZE); cropTail[0] = '\0';


    if (c < 2) {
        mainDir = ".";
        //mainDir = "C:\\Temp\\gmvault\\test\\db";
    } else {
        mainDir = args[1];
    }

    pDir = opendir (mainDir);
    if (pDir == NULL) {
        printf ("Cannot open directory '%s'\n", mainDir);
        return 1;
    }
    printf ("Processing main dir: '%s'\n", mainDir);

    while ((pDirent = readdir(pDir)) != NULL) {
        subDir = pDirent->d_name;
        if (strcmp(subDir, ".") && strcmp(subDir, "..")) {
            subDirFullPath[0] = '\0';
            strcat(subDirFullPath, mainDir);
            strcat(subDirFullPath, "\\");
            strcat(subDirFullPath, subDir);

            pSubDir = opendir (subDirFullPath);
            if (pSubDir == NULL) {
                printf ("Cannot open directory '%s'\n", subDirFullPath);
                return 1;
            }
            printf ("Processing subdir: '%s'\n", subDirFullPath);

            while ((pSubDirent=readdir(pSubDir)) != NULL) {
                fileName = pSubDirent->d_name;
                if (strcmp(fileName, ".") && strcmp(fileName, "..")) {
                    if(!strcmp(strrchr(fileName, '.'), ".meta")) {
                        fileFullPath[0] = '\0';
                        strcat(fileFullPath, subDirFullPath);
                        strcat(fileFullPath, "\\");
                        strcat(fileFullPath, fileName);

                        pFile = fopen(fileFullPath,"r");
                        if (pFile == NULL) {
                            printf ("Cannot open file '%s'\n", fileFullPath);
                            return 1;
                        }

                        //Read file contents
                        int i=0;
                        while( (fileChar = fgetc(pFile)) != EOF) {
                             fileText[i++] = fileChar;
						}
                        fileText[i++]='\0';

                        char* posCropRoot = strstr(fileText, "\"flags\": [");
                        char* posCropTail = strstr(fileText, "\"\\\\Seen\"]");

                        if(posCropRoot && posCropTail) {
                            if (posCropTail-posCropRoot>10) {
                                cropRoot[0] = '\0';
                                cropTail[0] = '\0';
                                int sizeCropRoot = posCropRoot-fileText+10;
                                strncpy(cropRoot, fileText, sizeCropRoot);
                                cropRoot[sizeCropRoot]='\0';
                                strcpy(cropTail, posCropTail);
                                fileText[0] = '\0';
                                strcat(fileText, cropRoot);
                                strcat(fileText, cropTail);
                                //printf("New fileText: '%s'\n", fileText);

                                //Save new file contents
                                fclose(pFile);
                                pFile = fopen(fileFullPath,"w");
                                i=0;
                                while ((fileChar = fileText[i]) != '\0') {
                                    fputc(fileChar, pFile);
                                    i++;
                                }
                                printf("!! File UPDATED: %s.\n", fileName);
                            } else {
                                printf("   File %s is OK. Nothing to do.\n", fileName);
                            }
                        }
                        fclose(pFile);
                    }
                }
            }
            closedir(pSubDir);
        }

    }
    closedir (pDir);
    return 0;
}`
