### ISSUE TITLE
error: command: UID => got more than 1000000 bytes

### ISSUE THREAD

**Issue by manuelmeurer** [gaubert/gmvault#345]
Since about 9 days I'm getting an error when running a Gmvault sync (quick or regular):

```
Start synchronization (2019-12-31T10h45m54s).


Start emails synchronization.
Error when reaching Gmail server. Wait 1 second(s) and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from /home/chief/.gmvault/myemail@gmail.com.oauth2.


Error when reaching Gmail server. Wait 2 second(s) and retry up to 2 times.
Disconnecting from Gmail Server and sleeping ...
Reconnecting to the from Gmail Server.
Get OAuth2 credential from /home/chief/.gmvault/myemail@gmail.com.oauth2.


Error when reaching Gmail server. Wait 4 second(s) and retry up to 2 times.
Error: command: UID => got more than 1000000 bytes.


=== Exception traceback ===
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 665, in _sync
    restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 626, in sync
    self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 589, in _sync_emails
    imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 435, in _common_sync
    imap_ids = self.src.search(imap_req)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/imap_utils.py", line 189, in wrapper
    reconnect(args[0], nb_tries, 2, err, m_sleep_time)
  File "/usr/local/lib/python2.7/dist-packages/gmvault-1.9.1-py2.7.egg/gmv/imap_utils.py", line 124, in reconnect
    raise rec_error
error: command: UID => got more than 1000000 bytes


=== End of Exception traceback ===
```

Before that, Gmvault ran without problems for years, and I haven't changed anything in the configuration recently.
I'm running v1.9.1 on Ubuntu 18.04.

Does anyone have an idea what the problem could be?

**Comment by jonahgraham** [comment]
Yes, either the amount of email you have or something else changed and gmail's response to a command is too big.

The way I worked around it is to add `imaplib._MAXLINE = 10000000` somewhere, such as right after the imort in imap_utils.py: https://github.com/gaubert/gmvault/blob/61a3f633a352503a395b7f5a0d9cf5fc9e0ac9b4/src/gmv/imap_utils.py#L30

See the comment in Python imaplib for more info: 
https://github.com/python/cpython/blob/9bfb4a7061a3bc4fc5632bccfdf9ed61f62679f7/Lib/imaplib.py#L46

**Comment by manuelmeurer** [comment]
Fantastic, thank you @jonahgraham, that worked like a charm! 😸
