### ISSUE TITLE
Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token

### ISSUE THREAD

**Issue by iamvishnurajan** [gaubert/gmvault#364]
Hi,

It seems something has changed on Google's end as of just a day or two ago. My last successful sync was on Feb 16. When trying to run gmvault now, it does not get past the Authorization.

Has anyone figured out a fix for this? Or is the only remaining option to do the app password authentication method?

Thanks, Vishnu

```
Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.

Error: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>.

=== Exception traceback ===
Traceback (most recent call last):
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 743, in run
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 235, in get_credential
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 411, in get_oauth2_credential
  File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 267, in _get_oauth2_acc_tok_from_ref_tok
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

=== End of Exception traceback ===
```

**Comment by iamvishnurajan** [comment]
Nevermind - this appears to be a network issue on my end. Closing ticket; sorry for the noise.
