### ISSUE TITLE
backup Trash & Spam folder

### ISSUE THREAD

**Issue by kstjtfcq** [gaubert/gmvault#88]
Hi!
My GMVault does not a backup of Trash & Spam folder ...
Do you know why?
Thank you,

**Comment by hardvain** [comment]
Any Updates on this issue? I am getting the following error:

```
 === Exception traceback ===
Traceback (most recent call last):
File "gmv/gmv_cmd.pyc", line 745, in run
File "gmv/gmv_cmd.pyc", line 621, in _restore
Dec 18 12:14:01 INAravindh.local gmv_runner[64738] <Notice>:   File "gmv/gmvault.pyc", line 882, in restore
File "gmv/gmvault.pyc", line 1146, in restore_emails
error: UID command error: BAD ['Invalid Arguments: Label name is not allowed: SPAM']
```
